<a href="https://colab.research.google.com/github/basudevm23/ML-Trial-and-Error/blob/main/SENTIMENT_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sentiment analysis
input will have text data
output will have 0 or 1 as positive or negative sentiment

we will form the vocab, each word is provided a vector
size different
we do padding
first we convert text to vectors

In [ ]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [ ]:
!pip install tensorflow

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

18

In [ ]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
sequences = pad_sequences(sequences, padding = 'post')

In [ ]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [ ]:
model = Sequential()
model.add(Embedding(19, output_dim=2, input_length=5))

model.summary

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


<bound method Model.summary of <Sequential name=sequential_6, built=False>>

In [ ]:
model.compile('adam', 'accuracy')

In [ ]:
pred= model.predict(sequences)
print(pred)
#each word is represented by 1x2 vector, even zeroes have their vectors

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
[[[ 0.02140016 -0.00106201]
  [-0.04037691 -0.03077224]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.00103771]]

 [[-0.04037691 -0.03077224]
  [-0.04037691 -0.03077224]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.00103771]]

 [[ 0.04797414  0.04867804]
  [ 0.04797414  0.04867804]
  [-0.02417874 -0.00494383]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.00103771]]

 [[ 0.02723909 -0.04814107]
  [ 0.02862498  0.03219802]
  [ 0.02723909 -0.04814107]
  [-0.04037691 -0.03077224]
  [ 0.02723909 -0.04814107]]

 [[ 0.01756282  0.04139617]
  [ 0.00447085 -0.04701031]
  [ 0.02684193  0.01211152]
  [-0.01051266  0.03010868]
  [ 0.04098724  0.00103771]]

 [[-0.02367277  0.0363141 ]
  [-0.02367277  0.0363141 ]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.00103771]]

 [[-0.00699456  0.0267023 ]
  [-0.00699456  0.0267023 ]
  [ 0.04098724  0.00103771]
  [ 0.04098724  0.0010377

In [ ]:
#inmd sentiment classfication dataset
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [ ]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

In [ ]:
X_train.shape

(25000,)

In [ ]:
X_test.shape

(25000,)

In [ ]:
X_train = pad_sequences(X_train, padding = 'post', maxlen=50)
X_test = pad_sequences(X_test, padding = 'post', maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [ ]:
# model = Sequential()
# model.add(SimpleRNN(32, input_shape = (50, 1), return_sequences=False))
# model.add(Dense(1, activation = 'sigmoid'))

# model.summary

#10000, 2, 50
# here 10000 is the vocabulary, 2 is the dimension of the output, and 50 is the input size
model = Sequential()
model.add(Embedding(10000, 2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation = 'sigmoid'))

50 time steps will be taking place
total weights=1088 in the simple rnn
total weights =33 in dense rnn

return sequences are kept false, becoz the output at the end of each time step is fed into the next time step
Ot-1 is used for Ot for finding new prediction value


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 24s 28ms/step - accuracy: 0.5258 - loss: 0.6903 - val_accuracy: 0.5733 - val_loss: 0.6666
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 31s 15ms/step - accuracy: 0.6360 - loss: 0.6363 - val_accuracy: 0.6276 - val_loss: 0.6362
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.7604 - loss: 0.4922 - val_accuracy: 0.7721 - val_loss: 0.4775
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.8658 - loss: 0.3227 - val_accuracy: 0.7948 - val_loss: 0.4867
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.9001 - loss: 0.2509 - val_accuracy: 0.7829 - val_loss: 0.4868
