In [2]:
import pandas as pd
import numpy as np

In [8]:
temp_df = pd.read_csv('IMDB Dataset.csv')

In [9]:
df = temp_df.iloc[:10000]

In [10]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
df.head(20)

review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
5   Probably my all-time favorite movie, a story o...  positive
6   I sure would like to see a resurrection of a u...  positive
7   This show was an amazing, fresh & innovative i...  negative
8   Encouraged by the positive comments about this...  negative
9   If you like original gut wrenching laughter yo...  positive
10  Phil the Alien is one of those quirky films wh...  negative
11  I saw this movie when I was about 12 when it c...  negative
12  So im not a big fan of Boll's work but then ag...  negative
13  The cast played Shakespeare.<br /><br />Shakes...  negative
14  This a fantastic movie of three prisoners who ...  positive
15  Kind of drawn in by the erotic scenes, only to...  negative
16  Some films just simply should not be remade. T...  positive
17  This movie made it into one of my top 10 most ...  negative
18  I remember this film,it was the first film i h...  positive
19  An awful film! It must have been up against so...  negative

In [12]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [13]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [15]:
df.isnull().sum()
#so no reviews are missing, all columns are filled

review       0
sentiment    0
dtype: int64

In [16]:
df.duplicated().sum()

17

In [17]:
df.drop_duplicates(inplace=True)

C:\Users\sukan\AppData\Local\Temp\ipykernel_13972\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [18]:
df.duplicated().sum()

0

In [19]:
#Basic Processing has been done on this text data
#Remove tags
#lowercase
#remove stopwords

In [26]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'),'', raw_text)
    return cleaned_text

In [27]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\sukan\AppData\Local\Temp\ipykernel_13972\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [28]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [29]:
df['review'] = df['review'].apply(lambda x:x.lower())

C:\Users\sukan\AppData\Local\Temp\ipykernel_13972\740760900.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [30]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

C:\Users\sukan\AppData\Local\Temp\ipykernel_13972\2826946130.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [31]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [32]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [33]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [34]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [36]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [37]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [38]:
y.shape

(9983,)

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [40]:
X_train.shape

(7986, 1)

In [41]:
# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
cv = CountVectorizer()

In [43]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [44]:
X_train_bow.shape

(7986, 48247)

In [52]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [54]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.627941912869304

In [55]:
confusion_matrix(y_test,y_pred)

array([[694, 291],
       [452, 560]], dtype=int64)

In [57]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8542814221331998

In [59]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8442663995993991

In [60]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8377566349524287

In [ ]:
## NOW WE WILL GO for TF IDF

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [61]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [62]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8497746619929895

In [ ]:
## NOW IT'S TIME FOR Word2Vec!!!!!

In [63]:
import gensim

In [64]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [65]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [66]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [67]:
model.build_vocab(story)

In [68]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5849784, 6186875)

In [69]:
len(model.wv.index_to_key)

31845

In [70]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [71]:
document_vector(df['review'].values[0])

array([ 0.04135974,  0.41163918,  0.16950834, -0.08214951,  0.00348306,
       -0.5296165 ,  0.15604515,  0.7758383 , -0.19647619, -0.19518727,
       -0.20329173, -0.5217232 ,  0.03656013,  0.1791    ,  0.2298869 ,
       -0.22699808,  0.14803115, -0.58387965, -0.02031377, -0.6602163 ,
        0.00433114,  0.09310002,  0.1708692 , -0.30507642, -0.19435917,
       -0.20131224, -0.26562974, -0.17762223, -0.34234944, -0.06225286,
        0.37105495,  0.15226288,  0.01991847, -0.13517588, -0.4459779 ,
        0.36556825,  0.01870171, -0.2582951 , -0.13746957, -0.7075267 ,
        0.1554663 , -0.3087713 , -0.1876057 , -0.00717065,  0.3701838 ,
       -0.11854985, -0.40592286, -0.14314242,  0.13791376,  0.24902458,
        0.1262102 , -0.25692037, -0.32535106, -0.15102726, -0.41285688,
        0.09238606,  0.3592835 ,  0.20801327, -0.3505857 ,  0.09441864,
       -0.09747164,  0.24389693, -0.21815394, -0.04722778, -0.3449246 ,
        0.42829987, -0.01252172,  0.1560651 , -0.5441377 ,  0.29

In [72]:
from tqdm import tqdm

In [73]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████████████████████████████████████████████████████████████████████████| 9983/9983 [09:35<00:00, 17.36it/s]


In [75]:
X = np.array(X)

In [77]:
X[0]

array([ 0.04135974,  0.41163918,  0.16950834, -0.08214951,  0.00348306,
       -0.5296165 ,  0.15604515,  0.7758383 , -0.19647619, -0.19518727,
       -0.20329173, -0.5217232 ,  0.03656013,  0.1791    ,  0.2298869 ,
       -0.22699808,  0.14803115, -0.58387965, -0.02031377, -0.6602163 ,
        0.00433114,  0.09310002,  0.1708692 , -0.30507642, -0.19435917,
       -0.20131224, -0.26562974, -0.17762223, -0.34234944, -0.06225286,
        0.37105495,  0.15226288,  0.01991847, -0.13517588, -0.4459779 ,
        0.36556825,  0.01870171, -0.2582951 , -0.13746957, -0.7075267 ,
        0.1554663 , -0.3087713 , -0.1876057 , -0.00717065,  0.3701838 ,
       -0.11854985, -0.40592286, -0.14314242,  0.13791376,  0.24902458,
        0.1262102 , -0.25692037, -0.32535106, -0.15102726, -0.41285688,
        0.09238606,  0.3592835 ,  0.20801327, -0.3505857 ,  0.09441864,
       -0.09747164,  0.24389693, -0.21815394, -0.04722778, -0.3449246 ,
        0.42829987, -0.01252172,  0.1560651 , -0.5441377 ,  0.29

In [78]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [79]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [80]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [81]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [82]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7781672508763144